project_name: gh-repomon

before:
  hooks:
    - go mod tidy
    - go test ./...

builds:
  - id: gh-repomon
    main: ./cmd/repomon
    binary: gh-repomon
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
      - arm64
    ldflags:
      - -s -w
      - -X main.version={{.Version}}
      - -X main.commit={{.Commit}}
      - -X main.date={{.Date}}

archives:
  - id: gh-repomon
    name_template: "{{ .ProjectName }}-{{ .Os }}-{{ .Arch }}"
    format: tar.gz
    format_overrides:
      - goos: windows
        format: zip
    files:
      - README.md
      - LICENSE
      - CHANGELOG.md

checksum:
  name_template: 'checksums.txt'
  algorithm: sha256

changelog:
  sort: asc
  use: github
  filters:
    exclude:
      - '^docs:'
      - '^test:'
      - '^chore:'
      - '^ci:'
  groups:
    - title: 'Features'
      regexp: '^feat.*'
      order: 0
    - title: 'Bug Fixes'
      regexp: '^fix.*'
      order: 1
    - title: 'Refactoring'
      regexp: '^refactor.*'
      order: 2
    - title: 'Performance Improvements'
      regexp: '^perf.*'
      order: 3
    - title: 'Other Changes'
      order: 999

release:
  github:
    owner: hazadus
    name: gh-repomon
  draft: false
  prerelease: auto
  mode: replace
  header: |
    ## GitHub Repository Activity Monitor - Release {{ .Tag }}

    This release includes binaries for multiple platforms. Download the appropriate binary for your system:

    - **Linux**: `gh-repomon-linux-amd64` or `gh-repomon-linux-arm64`
    - **macOS**: `gh-repomon-darwin-amd64` (Intel) or `gh-repomon-darwin-arm64` (Apple Silicon)
    - **Windows**: `gh-repomon-windows-amd64.exe` or `gh-repomon-windows-arm64.exe`

    ### Installation

    #### Via GitHub CLI Extension
    ```bash
    gh extension install hazadus/gh-repomon
    ```

    #### Manual Installation
    Download the appropriate binary for your platform and add it to your PATH.

    ### What's Changed

  footer: |
    **Full Changelog**: https://github.com/hazadus/gh-repomon/compare/{{ .PreviousTag }}...{{ .Tag }}

    ---

    For more information, see the [documentation](https://github.com/hazadus/gh-repomon/tree/main/docs).

# Snapshot configuration (for development builds)
snapshot:
  name_template: "{{ incpatch .Version }}-next"

# Announcement configuration (optional, for future use)
announce:
  skip: true
